Boutique/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^shop/', include('boutique1.urls', namespace='boutique1')),
    url(r'^', include('boutique1.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

boutique1/urls.py
from django.conf.urls import url
from . import views

app_name = 'boutique1'




urlpatterns = [
    #-------------------------------------------------------------------------------------------------------------------
    #Registration
    #-------------------------------------------------------------------------------------------------------------------
    url(r'^register/$', views.register, name='register'),
    url(r'^login_user/$', views.login_user, name='login_user'),
    url(r'^logout_user/$', views.logout_user, name='logout_user'),
    #-------------------------------------------------------------------------------------------------------------------
    #Discover
    #-------------------------------------------------------------------------------------------------------------------
    url(r'^$', views.discover, name='index'),
    url(r'^shop_products/(?P<shop_id>[0-9]+)/$', views.shopSProducts, name='shopSProducts'),
    url(r'^discover/(?P<category>[\w\-]+)/$', views.discover, name='discover_category'),
    url(r'^discover/$', views.discover, name='discover'),
    #-------------------------------------------------------------------------------------------------------------------
    #Shops
    #-------------------------------------------------------------------------------------------------------------------
    url(r'^myShops$', views.myShops, name='myShops'),
    url(r'^create_shop/$', views.create_shop, name='create_shop'),
    url(r'^edit_shop/(?P<shop_id>[0-9]+)/$', views.edit_shop, name='edit_shop'),
    url(r'^(?P<shop_id>[0-9]+)/delete_boutique/$', views.delete_shop, name='delete_shop'),
    url(r'^(?P<shop_id>[0-9]+)/$', views.shopDetails, name='shopDetails'),
    #-------------------------------------------------------------------------------------------------------------------
    #Products
    #-------------------------------------------------------------------------------------------------------------------
    url(r'^(?P<shop_id>[0-9]+)/product_detail/(?P<product_id>[0-9]+)/$', views.prodDetails, name='prodDetails'),
    url(r'^(?P<shop_id>[0-9]+)/duplicate_product/(?P<prod_id>[0-9]+)/$', views.duplicate_product, name='duplicate_product'),
    url(r'^(?P<shop_id>[0-9]+)/edit_product/(?P<prod_id>[0-9]+)/$', views.edit_product, name='edit_product'),
    url(r'^(?P<shop_id>[0-9]+)/create_product/$', views.create_product, name='create_product'),
    url(r'^(?P<shop_id>[0-9]+)/delete_product/(?P<product_id>[0-9]+)/$', views.delete_product, name='delete_product'),
    url(r'^product/(?P<id_product>[0-9]+)$', views.product, name='product'),
    url(r'^(?P<shop_id>[0-9]+)/product_status/(?P<prod_id>[0-9]+)/$', views.activate_product, name='activate_product'),
    #url(r'^(?P<shop_id>[0-9]+)/shop_products/(?P<product_id>[0-9]+)/$', views.shopSProducts, name='shopSProducts'),
    #-------------------------------------------------------------------------------------------------------------------
    #Collections
    #-------------------------------------------------------------------------------------------------------------------
    url(r'^(?P<shop_id>[0-9]+)/mycollections/$', views.myCollections, name='myCollections'),
    url(r'^(?P<shop_id>[0-9]+)/collections/details/(?P<coll_id>[0-9]+)$', views.collection_detail, name='collection_detail'),
    url(r'^(?P<shop_id>[0-9]+)/create_collection/$', views.create_collection, name='create_collection'),
    url(r'^(?P<shop_id>[0-9]+)/collections/edit/(?P<coll_id>[0-9]+)$', views.edit_collection, name='edit_collection'),
    url(r'^(?P<shop_id>[0-9]+)/collections/delete/(?P<coll_id>[0-9]+)$', views.delete_collection,
        name='delete_collection'),
    url(r'^(?P<shop_id>[0-9]+)/collection_status/(?P<coll_id>[0-9]+)/$', views.activate_collection, name='activate_collection'),
    #url(r'^collections/(?P<collection_id>[0-9]+)/$', views.detail_collection, name='collectionDetails'),
    #-------------------------------------------------------------------------------------------------------------------
    #Promotions
    #-------------------------------------------------------------------------------------------------------------------
    url(r'^(?P<shop_id>[0-9]+)/promotions/$', views.promotions, name='promotions'),
    url(r'^(?P<shop_id>[0-9]+)/promotions/new/$', views.create_promotion, name='create_promotion'),
    url(r'^(?P<shop_id>[0-9]+)/promotions/delete/(?P<promo_id>[0-9]+)$', views.delete_promotion,name='delete_promotion'),
    url(r'^(?P<shop_id>[0-9]+)/promotions/edit/(?P<promo_id>[0-9]+)$', views.edit_promotion, name='edit_promotion'),
    url(r'^(?P<shop_id>[0-9]+)/promotions/details/(?P<promo_id>[0-9]+)$', views.promotion_detail,name='promotion_detail'),
    #-------------------------------------------------------------------------------------------------------------------
    #REST API
    #-------------------------------------------------------------------------------------------------------------------  
    url(r'^create/$', views.ProductCreateAPIView.as_view(), name='create'),
    #-------------------------------------------------------------------------------------------------------------------
    #Albums
    #-------------------------------------------------------------------------------------------------------------------
    url(r'^(?P<shop_id>[0-9]+)/create_album/$', views.create_album, name='create_album'),
    url(r'^(?P<shop_id>[0-9]+)/all_albums/$', views.allAlbums, name='allAlbums'),
    url(r'^(?P<shop_id>[0-9]+)/albums/edit/(?P<album_id>[0-9]+)/$', views.edit_album, name='edit_album'),
    url(r'^(?P<shop_id>[0-9]+)/albums/delete/(?P<album_id>[0-9]+)/$', views.delete_album,name='delete_album'),
    url(r'^(?P<shop_id>[0-9]+)/album/details/(?P<album_id>[0-9]+)/$', views.albumDetails,name='albumDetails'),
    #-------------------------------------------------------------------------------------------------------------------
    #Pics
    #-------------------------------------------------------------------------------------------------------------------
    url(r'^(?P<shop_id>[0-9]+)/album/(?P<album_id>[0-9]+)/add_pic/$', views.add_pic, name='add_pic'),
    #url(r'^(?P<shop_id>[0-9]+)/all_albums/$', views.allAlbums, name='allAlbums'),
    #url(r'^(?P<shop_id>[0-9]+)/albums/edit/(?P<album_id>[0-9]+)/$', views.edit_album, name='edit_album'),
    url(r'^(?P<shop_id>[0-9]+)/album/(?P<album_id>[0-9]+)/delete_pic/(?P<pic_id>[0-9]+)/$', views.delete_pic,name='delete_pic'),
    #url(r'^(?P<shop_id>[0-9]+)/album/details/(?P<album_id>[0-9]+)$', views.albumDetails,name='albumDetails'),
    #-------------------------------------------------------------------------------------------------------------------
    #WishList
    #-------------------------------------------------------------------------------------------------------------------
    url(r'^create_wishcategory/$', views.create_wish_category, name='create_wish_category'),
    url(r'^my_categorys/$', views.my_categorys, name='my_categorys'),
    url(r'^delete_category/(?P<category_id>[0-9]+)/$', views.delete_category, name='delete_category'),
    url(r'^edit_category/(?P<category_id>[0-9]+)/$', views.edit_category, name='edit_category'),
    url(r'^category_add_product/(?P<category_id>[0-9]+)/$', views.create_wish_list, name='create_wish_list'),
    url(r'^add_product/(?P<category_id>[0-9]+)/(?P<prod_id>[0-9]+)/$', views.addprod, name='addprod'),
    url(r'^categoryProds/(?P<category_id>[0-9]+)/$', views.detailcategory, name='detailcategory'),
    url(r'^(?P<category_id>[0-9]+)/(?P<produit_id>[0-9]+)/delete_wishlist_produit/$', views.delete_category_produit,
        name='delete_category_produit'),

    url(r'^wishlist/$', views.create_wish_list, name='create_wish_list'),
]

boutique1/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Shop, Product, Trader, Picture, Collection, Promotion, Album, Pic, wish_category, wish_list


class ShopForm(forms.ModelForm):

    class Meta:
        model = Shop
        fields = ['name', 'logo', 'description', 'address']


class CollectionForm(forms.ModelForm):

    class Meta:
        model = Collection
        fields = ['title', 'description', 'product', 'image_collection', 'is_active']


#class PromotionForm(forms.ModelForm):
    # product = forms.ModelMultipleChoiceField(widget=forms.CheckboxSelectMultiple, queryset=Product.objects.all())

#    class Meta:
#        model = Promotion
#        fields = ['product','collection','discount_value', 'promotion_type', 'promotion_for', 'start_time', 'end_time', 'status']

class PromotionForm(forms.ModelForm):
    # product = forms.ModelMultipleChoiceField(widget=forms.CheckboxSelectMultiple, queryset=Product.objects.all())

    class Meta:
        model = Promotion
        fields = ['title','promotion_type', 'promotion_for','product','collection','discount_value','start_time', 'end_time']


class ProductForm(forms.ModelForm):

    class Meta:
        model = Product
        fields = ['name', 'description', 'product_type', 'price', 'principal_picture', 'category', 'quantity', 'is_active']


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email', 'password']

class TraderForm(forms.ModelForm):

    class Meta:
        model = Trader
        fields = ['picture', 'commercant_type', 'description', 'fb_link', 'instagram_link', 'location']


class PictureForm(forms.ModelForm):

    class Meta:
        model = Picture
        fields = ['name']

class AlbumForm(forms.ModelForm):

    class Meta:
        model = Album
        fields = ['title', 'description', 'album_image']


class PicForm(forms.ModelForm):

    class Meta:
        model = Pic
        fields = ['name', 'image', 'details']

class CategoryForm(forms.ModelForm):

    class Meta:
        model = wish_category
        fields = ['title', 'image_category','description','is_active']

class WishlistForm(forms.ModelForm):
    produit = forms.ModelMultipleChoiceField(
        queryset=Product.objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=True)

    class Meta:
        model = wish_list
        fields = ['wish_category','produit']


class WishlistForm1(forms.ModelForm):

    class Meta:
        model = wish_list
        fields = ['wish_category']

boutique1/templates/boutique1/add_pic.html
{% extends 'boutique1/base.html' %}
{% block title %}{{ prod }}{% endblock %}
{% load staticfiles %}
{% block body %}
    <div class="container-fluid songs-container">
        <div class="row">
            <div class="col-sm-4 col-md-3">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <a href="{% url 'boutique1:albumDetails' shop.id album.id %}">
                            {% if album.album_image %}
                                <img src="{{ album.album_image.url }}" class="img-responsive"
                                     style="width: 350px; height: 400px">
                            {% else %}
                                <h3>Image not found</h3>
                            {% endif %}
                        </a>
                        <table class="table">
                            <thead>
                            <tr>
                                <th>Details:</th>
                            </tr>
                            </thead>
                            <tbody>
                            <tr>
                                <td>Owner:</td>
                                <td>{{ album.owner.user.username }}</td>
                            </tr>
                            <tr>
                                <td>Album title:</td>
                                <td>{{ album.title }}</td>
                            </tr>
                            <tr>
                                <td>Description:</td>
                                <td>{{ album.description }}</td>
                            </tr>
                            <tr>
                                <td>Create date:</td>
                                <td>{{ album.create_date }}</td>
                            </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>

            <!-- Left Album Info -->
            <div class="col-sm-12 col-md-9">

        <!--<ul class="nav nav-pills" style="margin-bottom: 10px;">
                    <li role="presentation"><a href="{% url 'boutique1:shopDetails' shop.id %}">See All</a></li>
                    <li role="presentation" class="active"><a href="{% url 'boutique1:create_collection' shop.id%}">Add
                        Add</a></li>
                </ul>-->
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Add new pic</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'boutique1/form_template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Enter</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        </div>
    </div>
        {% endblock %}

boutique1/templates/boutique1/base.html
<!DOCTYPE html>
<html lang="en">
{% block head_imports %}
    <head>
        <meta charset="UTF-8">
        <title>Boutikti - {% block title %}{% endblock %}</title>
        {% load staticfiles %}

        <link rel="shortcut icon" type="image/png" href="{% static 'Grooveshark2.png' %}"/>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
        <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
        <link rel="stylesheet" type="text/css" href="{% static 'boutique1/style.css' %}"/>
        <link rel="stylesheet"
              href="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.2.3/jquery-confirm.min.css">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/5.0.0/normalize.min.css">
        <link rel='stylesheet prefetch'
              href='http://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css'>

        <!-- Vendor Styles including: Bootstrap, Font Icons, Plugins, etc.-->
        <link rel="stylesheet" media="screen" href="{% static 'boutique1/vendor.min.css' %}">
        <!-- Main Template Styles-->
        <link id="mainStyles" rel="stylesheet" media="screen" href="{% static 'boutique1/styles.min.css' %}">
        <!-- Customizer Styles-->
        {% comment %}<link rel="stylesheet" media="screen" href="{% static 'boutique1/customizer.min.css' %}">{% endcomment %}
        <!-- Google Tag Manager-->
        <script src="{% static 'boutique1/js/main.js' %}"></script>
    </head>
{% endblock %}
<body>
<nav class="navbar navbar-regular">
    <div class="container-fluid">

        <!-- Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'boutique1:discover' %}">Boutikti</a>
        </div>

        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class="{% block discover_active %}{% endblock %}"><a href="{% url 'boutique1:discover' %}"><span
                        aria-hidden="true"></span>&nbsp; Discover</a></li>
                <li class="{% block boutiques_active %}{% endblock %}"><a href="{% url 'boutique1:myShops' %}"><span
                        aria-hidden="true"></span>&nbsp; My Shops</a></li>
                {% comment %}<li class="{% block produits_active %}{% endblock %}"><a
                        href="{% url 'boutique1:myProducts' 'all' %}"><span aria-hidden="true"></span>&nbsp; My Products</a>
                </li>{% endcomment %}
            </ul>
            <form class="navbar-form navbar-left" role="search" method="get" action="{{ request.path }}">
                {% for key, value in request.GET.items %}
                    {% if key != 'page' and key != 'search' %}
                        <div class="u-form-group">
                            <input type="hidden" id="search_input" name="{{ key }}" value="{{ value }}"/>
                        </div>
                    {% endif %}
                {% endfor %}
                <div class="input-group">
                    <input type="text" class="form-control" id="search_input" placeholder="Search" name="search">
                    <div class="input-group-btn">
                        <button class="btn btn-default" type="submit"><i class="glyphicon glyphicon-search"></i>
                        </button>
                    </div>
                </div>
            </form>
            <ul class="nav navbar-nav navbar-right">
                {% ifequal shop0 0 %}
                    <li class="{% block add_Shop_active %}{% endblock %}"><a href="{% url 'boutique1:create_shop' %}">
                        <span aria-hidden="true"></span>&nbsp; Add Shop
                    </a>
                    </li>
                {% endifequal %}
                <li>
                    <a href="{% url 'boutique1:login_user' %}">
                        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Logout
                    </a>
                </li>
            </ul>
        </div>
    </div>
</nav>
{% block body %}
{% endblock %}

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.2.3/jquery-confirm.min.js"></script>
<script src='http://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js'></script>
<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootbox.js/4.4.0/bootbox.min.js"></script>

<!-- JavaScript (jQuery) libraries, plugins and custom scripts-->
<script src="{% static 'boutique1/js/vendor.min.js' %}"></script>
<script src="{% static 'boutique1/js/scripts.min.js' %}"></script>
<!-- Customizer scripts-->
<script src="{% static 'boutique1/js/customizer.min.js' %}"></script>

<!--<script type='text/javascript' src='http://code.jquery.com/jquery-1.10.2.min.js'></script>
<script src="{% static 'boutique1/js/jquery.countdown.min.js' %}"></script>-->

</body>
</html>

boutique1/templates/boutique1/create_shop.html
{% extends 'boutique1/base.html' %}
{% block add_Shop_active %}active{% endblock %}
{% block title %}Discover{% endblock %}

{% block body %}
<div class="container-fluid">

    <div class="row">

        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Ajouter Boutique</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'boutique1/form_template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Enter</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>

    </div>

</div>
{% endblock %}

boutique1/templates/boutique1/my_collections.html
{% extends 'boutique1/base.html' %}
{% block title %}{{ shop }}{% endblock %}
{% block boutiques_active %}active{% endblock %}

{% block body %}
    <div class="container-fluid songs-container">

        <div class="row">

            <!-- Left Album Info -->
            <div class="col-sm-4 col-md-3">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <a href="{% url 'boutique1:shopDetails' shop.id %}">
                            {% if shop.logo %}
                                <img src="{{ shop.logo.url }}" class="img-responsive"
                                     style="width: 350px; height: 400px">
                            {% else %}
                                <h3>Image not found</h3>
                            {% endif %}
                        </a>
                        <h1>{{ shop.name }} - {{ shop.owner.user.username }}</h1>
                        <table class="table">
                            <thead>
                            <tr>
                                <th>Details:</th>
                            </tr>
                            </thead>
                            <tbody>
                            <tr>
                                <td>Owner:</td>
                                <td>{{ shop.owner.user.username }}</td>
                            </tr>
                            <tr>
                                <td>Shop name:</td>
                                <td>{{ shop.name }}</td>
                            </tr>
                            <tr>
                                <td>Description:</td>
                                <td>{{ shop.description }}</td>
                            </tr>
                            <tr>
                                <td>Address:</td>
                                <td>{{ shop.address }}</td>
                            </tr>
                            <tr>
                                <td>Create date:</td>
                                <td>{{ shop.create_date }}</td>
                            </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>

            <!-- Right Product Info -->
            <div class="col-sm-8 col-md-9">

                <ul class="nav nav-pills" style="margin-bottom: 10px;">
                    <li role="presentation"><a href="{% url 'boutique1:shopDetails' shop.id %}">See All
                        </a></li>
                    <li role="presentation" class="active"><a href="{% url 'boutique1:myCollections' shop.id %}">My Collections</a>
                    </li>
                </ul>

                <div class="panel panel-default">
                    <div class="panel-body">

                        <div class="col-sm-3 pull-right">
                        <form action="{% url 'boutique1:create_collection' shop.id %}" method="" style="display: inline;">
                            <button class="btn btn-xs" style="color: green;height: 40px;width: 200px">
                                <span class="glyphicon glyphicon-plus-sign"></span> Add Collection
                            </button>
                        </form>
                    </div>

                        <h3>My Collecions</h3>

                        {% if error_message %}
                            <p><strong>{{ error_message }}</strong></p>
                        {% endif %}

                        <table class="table">
                            <thead>
                            <tr>
                                <th>Colection name</th>
                                <th>Description</th>
                                <th>Collection picture</th>
                                <th>Status</th>
                                <th>Actions</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for c in collection.all %}
                                <tr>
                                    <td>{{ c.title }}</td>
                                    <td>{{ c.description }}</td>
                                    <td>
                                        <a href="{% url 'boutique1:collection_detail' shop.id c.id %}">
                                            <img src="{{ c.image_collection.url }}" class="img-responsive"
                                                 style="width: 50px; float: left; margin-right: 10px;"/>
                                        </a>
                                        <a href="{% url 'boutique1:collection_detail' shop.id c.id %}">{{ c.title }}</a>
                                    </td>
                                    <td>
                                        {% if c.is_active %}
                                            <p class="list-group-item-text">
                                                <span class="label label-success">Active</span>
                                            </p>
                                        {% else %}
                                            <p class="list-group-item-text">
                                                <span class="label label-danger">Not Active</span>
                                            </p>
                                        {% endif %}
                                    </td>
                                    <td>
                                        <form action="{% url 'boutique1:delete_collection' shop.id c.id %}"
                                              method="POST" style="display: inline;">
                                            {% csrf_token %}
                                            <input type="hidden" name="product_id" value="{{ c.id }}"/>
                                            <button type="submit" class="btn btn-danger btn-xs" name="remove_levels"
                                                    value="delete"
                                                    onclick="return confirm('Are you sure you want to delete this item?');">
                                                <span class="glyphicon glyphicon-remove"></span> Delete
                                            </button>
                                        </form>
                                        {% comment %}<form action="{% url 'boutique1:duplicate_product' shop.id c.id %}"
                                              method="GET" style="display: inline;">
                                            {% csrf_token %}
                                            <input type="hidden" name="product_id" value="{{ c.id }}"/>
                                            <button type="submit" class="btn btn-primary btn-xs" name="remove_levels"
                                                    value="delete">
                                                <span class="glyphicon glyphicon-duplicate"></span> Duplicate
                                            </button>
                                        </form>{% endcomment %}
                                        <form action="{% url 'boutique1:edit_collection' shop.id c.id %}"
                                              method="GET" style="display: inline;">
                                            {% csrf_token %}
                                            <input type="hidden" name="produit_id" value="{{ c.id }}"/>
                                            <button type="submit" class="btn btn-warning btn-xs" name="remove_levels"
                                                    value="Edit">
                                                <span class="glyphicon glyphicon-edit"></span> Edit
                                            </button>
                                        </form>

                                        <form action="{% url 'boutique1:collection_detail' shop.id c.id %}"
                                              method="GET" style="display: inline;">
                                            {% csrf_token %}
                                            <input type="hidden" name="product_id" value="{{ c.id }}"/>
                                            <button type="submit" class="btn btn-info btn-xs" name="remove_levels"
                                                    value="delete">
                                                <span class="glyphicon glyphicon-info-sign"></span> Details
                                            </button>
                                        </form>

                                        <form action="{% url 'boutique1:activate_collection' shop.id c.id %}"
                                              method="GET" style="display: inline;">
                                            {% csrf_token %}
                                            <input type="hidden" name="coll_id" value="{{ c.id }}"/>
                                            {% if c.is_active %}
                                                <button type="submit" class="btn btn-danger btn-xs" name="remove_levels"
                                                        value="delete">
                                                    <span class="glyphicon glyphicon-ban-circle"></span>
                                                    Deactivate
                                                </button>
                                            {% else %}
                                                <button type="submit" class="btn btn-success btn-xs"
                                                        name="remove_levels"
                                                        value="delete">
                                                    <span class="glyphicon glyphicon-ok-circle "></span>
                                                    Activte
                                                </button>
                                            {% endif %}
                                        </form>
                                    </td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>

                    </div>
                </div>

            </div>

        </div>
    </div>
{% endblock %}